spring:
  application:
    name: kafka-practice

  kafka:
    bootstrap-servers: localhost:9092 # 1. ??? ???? ?? ??

    # 2. ????(Producer) ??
    producer:
      # ??? Key/Value? ???? ???? ???(Serializer) ??? ??
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      # (??) ?????? ??? ???? ?? (all: ??? ??? ?? ?? ??)
      acks: all

    # 3. ???(Consumer) ??
    consumer:
      # ??? ?? ID (??)
      group-id: my-group
      # ?????? ?? ???? ??? ???? ????(Deserializer) ??? ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # (??) ?? ?? ? ?? ??? ?? (earliest: ?? ??? ?????)
      auto-offset-reset: earliest

